name: Publish

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    #  with:
    #    fetch-depth: 2
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{secrets.FTP_SERVER}}/public_html
        ftp-username: ${{secrets.FTP_USERNAME}}
        ftp-password: ${{secrets.FTP_PASSWORD}}